### ISSUE TITLE
Arguments to nekrs::setup() in main()

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/nekRS#111]
I think that, in `main()`, `nekrs::setup()` is called with incorrectly-ordered arguments.  The call is:

https://github.com/Nek5000/nekRS/blob/ecd93515c6f662f470693f9f042b48bb2f6ef07b/src/main.cpp#L124-L126

But the function declaration is:

https://github.com/Nek5000/nekRS/blob/ecd93515c6f662f470693f9f042b48bb2f6ef07b/src/nekrs.hpp#L9-L11

**Comment by RonRahaman** [comment]
Actually, I just saw that the definition is consistent with the call.  But I think the variable names in the header should be fixed, just to avoid confusion for anyone reading the code:

https://github.com/Nek5000/nekRS/blob/ecd93515c6f662f470693f9f042b48bb2f6ef07b/src/nekrs.cpp#L25-L27

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/c4e36cfaf992de47a4ec2b12d4d2f83294ca7d99
