### ISSUE TITLE
Renaming `libP/include/types.h`

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/nekRS#128]
Would you consider renaming [`src/libP/include/types.h`](https://github.com/Nek5000/nekRS/blob/master/src/libP/include/types.h) to avoid confusion with UNIX's [`sys/types.h`](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/types.h.html)?

I don't think the libP header will conflict with any programs that also include the UNIX header, since (as far as I can tell), the UNIX header will need to be included along with its subdirectory (`#include <sys/types.h>`).  Just wondering if you'd consider it.

**Comment by stgeke** [comment]
Resolved in https://github.com/Nek5000/nekRS/commit/04376d8abcec7c162511f889803352d4b9e0516c
