### ISSUE TITLE
lxd in logfile?

### ISSUE THREAD

**Issue by fischer1** [Nek5000/nekRS#133]
We currently get lx1,lx2,lx3 in the logfile.

Can we also add lxd to the same line (both for Nek5000 and NekRS) ?

**Comment by stgeke** [comment]
For Nek5000 we use always lxd=1 to save memory(it's not used anywhere). For nekRS we print it already - look for cubNq.

**Comment by fischer1** [comment]
In Nek5000, most people set lxd ~ (3*lx1)/2 ?

Could we please add lxd to the lx1 line in NekRS?

**Comment by fischer1** [comment]
And to Nek5000?

**Comment by fischer1** [comment]
I'm guessing lxd=1 in NekRS, not Nek5000?

**Comment by stgeke** [comment]
https://github.com/Nek5000/Nek5000/commit/b10b1927ab87cbebf06b0fbe4a23523e51e099c1
