### ISSUE TITLE
Unexpected bc.id in user boundary functions

### ISSUE THREAD

**Issue by stgeke** [Nek5000/nekRS#135]
We prioritize Dirichlet over Neumann for shared edges. Currently this triggers calls to the user Dirichlet function with an unexpected bc.id for the overruled Neumann point.

**Comment by fischer1** [comment]
We can handle this as is done in Nek5000 using a combination of dsop and a mask.

Nek5000 never calls the userbc for a Neuman face.

**Comment by stgeke** [comment]
Yeah I am aware of this. It's just here for book keeping reasons.

**Comment by stgeke** [comment]
https://github.com/Nek5000/nekRS/commit/d9c871f81ff4a55641c333b42859a06b3907ee54
