### ISSUE TITLE
Mesh contains NULL values?

### ISSUE THREAD

**Issue by mvictoras** [Nek5000/nekRS#176]
I was getting some funky results with the mesh, and I added this code in nekrs::setup to debug.
If you add this:
```
mesh_t *mesh = ins->mesh;
  int csize = mesh->Nelements*mesh->Nverts;
  for(int i=0; i<csize; ++i) {
    if(mesh->EX[i] == NULL || mesh->EY[i] == NULL || mesh->EZ[i] == NULL) {
      cout << "Found NULL in mesh at index: " << i << endl;
    }
  }
```

right after this code:
```
if(ins->Nscalar) {
    ins->cds->o_S.copyFrom(ins->cds->S);
    ins->cds->o_prop.copyFrom(ins->cds->prop);
  }
```
you will see that some values are NULL.
Is this normal? Am I doing something wrong?

Master branch.

PS: I am running the ethier example

**Comment by stgeke** [comment]
Not sure what you're trying to do. Looks like you want to check if an element vertex coordinate is zero? It doesn't surprise me that this is the case in the ethier mesh.

**Comment by mvictoras** [comment]
I am trying to visualize the mesh. If I run ethier on Nek5000, I can export the mesh (with custom code) and I see a sphere.

When I do the same with NekRS, I get a lot of NULLs and the mesh is a mess. 
What is the vertices order in NekRS? I am assuming it is a hexahedron and that the order is like the image below:

<img width="149" alt="hexahedron" src="https://user-images.githubusercontent.com/1523876/100656502-73ca5580-3312-11eb-8770-3ae22fb973d3.png">

**Comment by mvictoras** [comment]
@stgeke any thoughts?
