### ISSUE TITLE
NekRS only supports GNU compilers

### ISSUE THREAD

**Issue by fab6** [Nek5000/nekRS#177]
Hi,
I am not able to compile on a macos system with 

![image](https://user-images.githubusercontent.com/3047695/100467976-c23de100-30d3-11eb-9438-a7f6c1f358dc.png)

`
gfortran --version
GNU Fortran (Homebrew GCC 10.2.0) 10.2.0
`

Unfortunately I get:
`
 CMake Error at CMakeLists.txt:59 (message):   NekRS only supports GNU compilers
`

![image](https://user-images.githubusercontent.com/3047695/100467933-af2b1100-30d3-11eb-9564-38819b2144ea.png)

Do you have an idea or suggestion?

Thank you!
Fab

**Comment by stgeke** [comment]
We only support GNU but you're using Clang for C/CXX. Moreover you should set NEKRS_CC etc. to the corresponding MPI wrappers.

**Comment by fab6** [comment]
ok, thank you very much! I think I see it now on top it says AppleClang.
