### ISSUE TITLE
finalTime should be consistent with NtimeSteps

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#179]
If the user-specified end time is not evenly divisible by the requested `dt`, currently the number of time steps is modified without also updating the `ins->finalTime` to be consistent. This should be corrected - 

1. For fixed time stepping, this can be accomplished by setting `ins->finalTime = ins->dt * ins->NtimeSteps`, or
2. For adaptive time stepping, this can be accomplished by setting the last time step equal to `ins->dt = ins->finalTime - time`.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/9c31c6246e811afa177bfc6bd706176a87a405b5
