### ISSUE TITLE
Remove presTOL and velTOL

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#181]
In `ellipticSolve`, we call `options.getArgs("SOLVER TOLERANCE", tol)` to grab the residual tolerance. But the function call is confusing, because you _pass in_ a tolerance, which gives the reader the impression that `ins->presTOL` and `ins->velTOL` hold meaningful information. But this isn't the case - I think this is probably an artifact from before nekRS could accommodate user-specified residual tolerances?

Two possible resolutions:

1) Delete `ins->presTOL` and `ins->velTOL` as parameters, and change the function parameters for `ellipticSolve` to not take a tolerance as input (since it is currently meaningless), _or_

2) Assign the user-specified tolerances to `ins->presTOL` and `ins->velTOL`, and then remove the `getArgs("SOLVER TOLERANCE", tol)` line in `ellipticSolve` so that the tolerances passed into `ellipticSolve` are actually used.

It would also be nice for consistency purposes to require the user to set `residualTol` for each of the scalars - I _think_ the current implementation does use `cds->TOL` if the user doesn't specify `residualTol`, but this can hide what is actually going on and is unexpected when you are required to set `residualTol` for the velocity and pressure.

**Comment by stgeke** [comment]
https://github.com/Nek5000/nekRS/commit/9c31c6246e811afa177bfc6bd706176a87a405b5
