### ISSUE TITLE
Support for userParam's in UDF

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#182]
Nek5000 allows you to use user-defined parameters in the `.par` file that you can then access and use programmatically from user-defined functions. We should allow a similar capability in nekRS. If a user sets `userParam01 = 0.5` in the `.par`, we should be able to retrieve it from the `.udf` file with something like:

```
dfloat my_var;
options.getArgs("USERPARAM01", my_var);
```

This would greatly reduce the JIT compilation time for users who want variable inputs for things like the inlet velocity.

**Comment by stgeke** [comment]
Users can define their own parameters in the .par file. In the .udf one can simply access it using e.g. `nrs->par->extract("section", "key", value)`
