### ISSUE TITLE
Implement A-conjugate solution projection

### ISSUE THREAD

**Issue by MalachiTimothyPhillips** [Nek5000/nekRS#187]

**Comment by MalachiTimothyPhillips** [comment]
This allows us to only store X (not B) in solution projection to reduce memory footprint. See: https://www.sciencedirect.com/science/article/pii/S0045782598000127

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/7a55f459cd9b42129d0d3312dac8dd614cdb50d0
