### ISSUE TITLE
[par file] The argument of the startFrom is converted to lowercase

### ISSUE THREAD

**Issue by yslan** [Nek5000/nekRS#194]
The name of the restart file will be converted into lower case, and the code won't find the file

For example, `startFrom = AaBbCc.fld` will show in the logfile as
```
 Reading checkpoint data
/gpfs/mira-home/ylan/nekrs_repo1106/examples/turbPipe/aabbcc.fld
```

**Comment by stgeke** [comment]
All keys in par are case insensitive and will be casted to lowercase internally. If you don't want that put the the key in quotes (startFrom = "AaBbCc.fld").

**Comment by yslan** [comment]
Got it!
