### ISSUE TITLE
par KEYS are not validated

### ISSUE THREAD

**Issue by stgeke** [Nek5000/nekRS#2]

**Comment by aprilnovak** [comment]
Along similar lines, it would be nice to warn the user if they have something like

`options.getArgs("SCALAR00 RHOCP", rho_cp);`

if `RHOCP` is an invalid key. Currently no warning prints, it just assigns some random value to `rho_cp`.

**Comment by tcew** [comment]
fwiw in the libParanumal refactor all settings need to be registered before they can be assigned values or retrieved:

https://github.com/paranumal/libparanumal/blob/master/libs/core/settings.cpp

**Comment by aprilnovak** [comment]
That's a great feature. @stgeke, what is the motivation again for not having libParanumal as a submodule or fetched during build with `FetchContent`? It would be nice to quickly take advantage of improvements like this.

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/7a55f459cd9b42129d0d3312dac8dd614cdb50d0
