### ISSUE TITLE
Increase default verbosity of elliptic solver

### ISSUE THREAD

**Issue by fischer1** [Nek5000/nekRS#216]
We need, e.g., for the pressure solve, all of the information given in nek5000, for each step:

         17  Project PRES           2.4062E-01   4.9165E-01   2.0433E+00  12  40
         17  U-PRES gmres       9   9.3593E-05   6.5623E-04   1.0000E-04   5.8138E-02   2.2332E-01
  
This should be the _default. 

WHY?

Because, current NekRS runs are at the large end of the spectrum in size, compared to Nek5000
cases.   Thus, each is a hero calculation, involving many unknowns (e.g., broken meshes, etc.)

These large jobs sit in the queue for days.

Then the logfile produces almost no data --- when we see large iteration counts we do not know
if it is because the preconditioner is ineffective of whether it's because the initial residual is
large.  We also have no idea of whether the pressure projection is working or not.

**Comment by fischer1** [comment]
Logfiles should default to informative.

If you want them to be fast, we could, for example, default to turning down verbosity
after a default value of 100 steps.

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/0a1d5aeded174a7df8ac44f2608039f5ec62c4e0
