### ISSUE TITLE
Mesh connectivity

### ISSUE THREAD

**Issue by Metalcycling** [Nek5000/nekRS#230]
Hi,

I created a very simple case of a square with 4x4 elements and Dirichlet (i.e., O) boundary conditions all around. The code fails with Jacobian errors and produces the following output:

![Screenshot from 2021-02-17 10-40-24](https://user-images.githubusercontent.com/4558556/108236606-b67b1d00-710c-11eb-9671-3c60c5f5a427.png)

The sames files work fine with Nek5000, so I don't know what is happening. I'm attaching the case files here.

Thanks,
Pedro

[mesh.zip](https://github.com/Nek5000/nekRS/files/5997205/mesh.zip)

**Comment by stgeke** [comment]
We only support 3D meshes.
Please join us on Slack to discuss issues like this.
