### ISSUE TITLE
Cannot have empty .usr file

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#242]
If you have an empty .usr file in your case directory, even if there's nothing in it, you get a JIT-time error related to not finding the usrdat_ symbol. Ideally, there shouldn't be any error because the file is empty and the user should have everything set up in the .udf/.oudf files instead.

```
Initializing device
building udf ... done (2.14441s)
building nek ... done (13.7834s)

loading nek ...
/home/anovak/cardinal/test/tests/cht/nondimensional/.cache/nek5000/libsfr_pin_turb.so: undefined symbol: usrdat_
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
```

**Comment by stgeke** [comment]
I don't see a good reason to have an empty usr file - no .usr file will do the trick.

**Comment by aprilnovak** [comment]
It's more so that the user might make a mistake and have an empty file, but would get this somewhat cryptic message.

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/0a1d5aeded174a7df8ac44f2608039f5ec62c4e0
