### ISSUE TITLE
vanishing Jacobian

### ISSUE THREAD

**Issue by tonyzahtila** [Nek5000/nekRS#243]
Hi I am having two separate issues,

a) I am trying to run an example case, no matter which I select, be it turbPipe or ethier, I get a vanishing Jacobian error.

b) If I am to run with more than 1 cpu rank, say, "nrsmpi ethier 2" (with 1 GPU requested by the slurm script), I get the following error, 

Initializing device
terminate called after throwing an instance of 'occa::exception'
  what():
---[ Error ]--------------------------------------------------------------------
    File     : /data/cephfs/punim0524/nek/nekRS/3rd_party/occa/src/modes/cuda/device.cpp
    Line     : 30
    Function : device
    Message  : Device: Creating Device
               CUDA Error [ 101 ]: CUDA_ERROR_INVALID_DEVICE
    Stack
      10 occa::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
       9 occa::cuda::error(cudaError_enum, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
       8 occa::cuda::device::device(occa::properties const&)
       7 occa::cuda::cudaMode::newDevice(occa::properties const&)
       6 occa::device::setup(occa::properties const&)
       5 occaDeviceConfig(setupAide&, ompi_communicator_t*)
       4 nekrs::setup(ompi_communicator_t*, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
       3 /home/tzahtila/.local/nekrs/bin/nekrs()
       2 /lib64/libc.so.6(__libc_start_main+0xf5)
       1 /home/tzahtila/.local/nekrs/bin/nekrs()

Additionally, I am not able to click the link to message the nekRS mailing list.

Kind regards, 

Tony

**Comment by stgeke** [comment]
Please use GitHub Discussions for request like this.

**Comment by stgeke** [comment]
You should open 2 separate discussions for this.

**Comment by tonyzahtila** [comment]
Thank you, I have now split it into two discussions.
