### ISSUE TITLE
Negative time step in par file

### ISSUE THREAD

**Issue by MartinKarp** [Nek5000/nekRS#266]
When trying to run a case from Nek5000 one inconvenience I find is that to have a constant dt in Nek5000 one specifices `dt = -1e-3` in the .par file in order to have a constant time step of 1e-3. 

If one then uses this file in NekRS the solver tries to runs backwards in time, without any error message, and crashes. It would be very convenient if there was a check for negative time steps in NekRS.

It is quite minor but would remove some unnecessary troubleshooting when setting up a case.

**Comment by stgeke** [comment]
Agreed. However keep in mind that the par file of two codes is similar but not fully compatible.

**Comment by MartinKarp** [comment]
Absolutely, but this is a change that I found was easily overlooked.

**Comment by stgeke** [comment]
https://github.com/Nek5000/nekRS/compare/221a9959cec5...9198502187a1
