### ISSUE TITLE
Error checking for standard oudf function names

### ISSUE THREAD

**Issue by KrausAdam** [Nek5000/nekRS#271]
For example if there is the typo "VelocityDirichletConditions" instead of the correct "velocityDirichletConditions", the boundary conditions in that block will not be applied, but the code will run without issue or error message. This can result in effects that are difficult to debug.

**Comment by stgeke** [comment]
We have to think about a good way to check this. Functions like velocityDirichletConditions() are optional so we cannot simply look if this functions exists in oudf.

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/7a55f459cd9b42129d0d3312dac8dd614cdb50d0
