### ISSUE TITLE
Add par option preconditioner = auto

### ISSUE THREAD

**Issue by stgeke** [Nek5000/nekRS#323]
Test different preconditioners or configurations during setup or at a given time instant (e.g. step 500):

pMG/AMG preconditioner
- Number of pMG levels
- Smoother (CHEB+JAC, CHEB+ASM, CHEB+RAS, ASM, RAS)
- Chebyshev eigenvalue bounds and smoother sweeps (can vary across different pMG levels down/up in the Vcycle)
- Coarse grid solver (CHEB+JAC, AMG, SEMFEM) + settings

SEMFEM
- AMG solver settings

To reduce the size of the parameter space we should limit ourselves to "promising" candidates.

**Comment by fischer1** [comment]
Is this accompanied by a

preconditioner = auto

flag in .par?
________________________________
From: stgeke ***@***.***>
Sent: Friday, June 11, 2021 8:48 AM
To: Nek5000/nekRS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Nek5000/nekRS] preconditioner = auto (#323)


Test different preconditioner/configurations during setup e.g.:

  *   Cheby1 + RAS
  *   Cheby2 + RAS
  *   Cheby1 + ASM
  *   Cheby2 + ASM
  *   SEMFEM

This will increase the setup cost. Moreover the optimal choice might dependent on the RHS.

**Comment by stgeke** [comment]
Yes this will be the idea once it's implemented.

**Comment by stgeke** [comment]
Tracked internally.
