### ISSUE TITLE
Allow capital letters in restart file names

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#341]
If you try to use a restart file with a capital letter (like `Re1000.fld`), nekRS throws an unhelpful abort message:

```
 Reading checkpoint data
/home/anovak/problems/msm_sfr_7pin/re1000.fld
byte_read() :: fopen failure2!
ERROR: Error reading restart header in mfi_prepare  ierr=  1
```

**Describe the solution you'd like**
NekRS should either print a useful error message that makes it clear that the source of the error is capitalization (and not any of the contents of the restart file itself), or else allow files with capital letters.

**Comment by emerzari** [comment]
I have to admit that I got burned by this a few times already.

**Comment by yslan** [comment]
The capital letter is supported if you use double quotation.

```
restartFrom = "Re1000.fld"   # This reads Re1000.fld
restartFrom = Re1000.fld     # This reads re1000.fld
```

**Comment by emerzari** [comment]
Yes, but I think the point is that the error is really not informative if you use the incorrect syntax. I think it would be nice to a warning if the name of the restart file has a capital letter. 

It drove me crazy a few times until I realized my mistake later. It’s not uncommon to have other issues with the file system. 

But I also think that when the documentation is up and running this should be a lesser issue.

**Comment by stgeke** [comment]
Key/value pairs in par are case insensitive unless you use "value".
Print a warning that the restart file has a capital letter doesn't make sense too me. However we should improve the error message that the file was not found instead of "ERROR: Error reading restart header in mfi_prepare". However that's something in nek5000.
