### ISSUE TITLE
[EXPERIMENTAL][SOLVERS] Investigate recycled krylov subspace scheme

### ISSUE THREAD

**Issue by MalachiTimothyPhillips** [Nek5000/nekRS#343]
The schemes considered in the attached paper _may_ be an improvement to the current solution projection schemes we use.

[Recycling Krylov Subspaces for Sequences of Linear Systems](https://github.com/Nek5000/nekRS/files/6849520/040607277.pdf)

**Comment by stgeke** [comment]
Track internally.
