### ISSUE TITLE
Process command queue at runtime (similar to nek's ioinfo)

### ISSUE THREAD

**Issue by MalachiTimothyPhillips** [Nek5000/nekRS#357]
It seems like there may be some interest in providing something like nek500's ioinfo.

**Comment by stgeke** [comment]
I suggest to add something more generic:

The can define a command queue in a file (nrs.cmd):
```
CHECKPOINT
END
```

Command Examples
* SET dt = 1e-2
* SET numSteps = 1000
* SET writeInterval = 100
* SET verbose = true
* PRINT runtimeStates
* END
* CHECKPOINT
* tbd

If the signal SIGUSR2 is received the command queue is being processed.

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/7a55f459cd9b42129d0d3312dac8dd614cdb50d0
