### ISSUE TITLE
Add coordinates to first avg field file 

### ISSUE THREAD

**Issue by MalachiTimothyPhillips** [Nek5000/nekRS#365]
Avg statistics are in 64-bit precision by default. However, the regular field files are stored in 32-bit precision. This workflow proves to be a pain point for some users, as the coordinates are not available in the avg statistics. Adding the coordinates to the first avg field file (or, alternatively, all field files in the ALE case) would alleviate this issue.

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/7a55f459cd9b42129d0d3312dac8dd614cdb50d0
