### ISSUE TITLE
update nrsqsub_summit for updated SUMMIT system

### ISSUE THREAD

**Issue by yhaomin2007** [Nek5000/nekRS#368]
nrsqsub_summit needs to be modified for updated summit system.
other wise get errors:

#######################################################
###      1 ERROR(S) FOUND.  JOB NOT SUBMITTED.       ###
30: The '-n <slots>' flag is no longer supported.  Please use '-nnodes <node_count>' to request nodes.
Please address the given error(s) and resubmit.

**Comment by stgeke** [comment]
Closing it for now - not reproduceable anymore.
