### ISSUE TITLE
Add #calls to runtime statistics

### ISSUE THREAD

**Issue by fischer1** [Nek5000/nekRS#387]
setup                 1.87389e+02s (1.83)
    loadKernels         8.03903e+01s (0.79)
  udfExecuteStep        3.40134e-03s (0.00)
  solve step min/max    1.55650e-01s / 2.37318e-01s (first 10 steps excluded)
  total solve           1.02377e+02s
    makef               2.19445e+01s (0.21)
      udfUEqnSource     2.04153e-01s (0.00)
    velocitySolve       1.08192e+01s (0.11)
    pressureSolve       5.10852e+01s (0.50)
      preconditioner    3.75489e+01s (0.37)
        pMG smoother    2.20148e+01s (0.22)
        coarse grid     1.23455e+01s (0.12)
      projection        2.47380e+00s (0.02)
    scalarSolve         3.82929e+00s (0.04)
      makeq             9.74556e+00s (0.10)
    udfProperties       4.68288e-03s (0.00)

Could we have "number of calls" at the  front of each line for these stats ?

That way, one would know, e.g., how many pressure iterations used for the entire run, because preconditioner would have a prefix like:

 preconditioner     12137        3.75489e+01s (0.37)

etc.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/9ae887200454a3409e8a0c324bde9989815716c3
