### ISSUE TITLE
Error while reading SESSION.NAME!  

### ISSUE THREAD

**Issue by jigo3635** [Nek5000/nekRS#411]
Hi,

I tried to run case `$NEKRS_HOME/examples/turbPipePeriodic` using nekRS v21.1 but got error

> 
> $ ~/.local/nekrs/bin/nrsmpi turbPipe 2
> ...
> Scanning dependencies of target UDF
> 
> [100%] Built target UDF
> done (2.22212s)
> building nek for lx1=8, lelt=3923 and lelg=7840 ...
> done
> done (38.4338s)
> loading nek ...
> 
> ERROR:  Error while reading SESSION.NAME!  ierr=***
> 
> an error occured: dying ...
> ...
> 

Even I wrote `SESSION.NAME` with the casename and path likes nek5000, there is still the error.  Is the file SESSION.NAME still required in nekRS? 

Thanks. /Jing

**Comment by stgeke** [comment]
Out of curiosity - what was the issue here?

**Comment by jigo3635** [comment]
A module with int64 has been occidentally added.  I should have not reported the issue since it  can be checked with the error code "ierr=***".  /Jing
