### ISSUE TITLE
Warn for unmapped boundary IDs

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#415]
For complex meshes, it's possible for extraneous sidesets to exist in the mesh, possibly as artifacts of the mesh generation process (e.g. stitching). Users may also sometimes define sidesets for postprocessing operations, such as visualizing the solution on a complex surface. However, NekRS currently aborts if there is a sideset ID in the mesh that isn't mapped to a boundary condition. We can change the error into a warning instead to provide more flexibility in meshing.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/9ae887200454a3409e8a0c324bde9989815716c3
