### ISSUE TITLE
Restoring constant flow rate diagnostics from Nek5000

### ISSUE THREAD

**Issue by kent0** [Nek5000/nekRS#416]
Currently, the constant flow rate option results in only `constantFlowScale` and `flowRateError` being displayed at each timestep. Nek5000  displays the timestep, direction, `delta_flow`, `current_flow`, and the prescribed `flow_rate` in the following fashion:

          1  Volflow Z              1.9000E+01   1.4217E-02   3.4874E-06   7.8539E-01   7.8540E-01

These values are important for understanding the state of the unmodified solution and the flow rate correction.

cc'ing @fischer1

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/9ae887200454a3409e8a0c324bde9989815716c3
