### ISSUE TITLE
Incorrect flowrate with the constant flow rate option + CHT

### ISSUE THREAD

**Issue by kent0** [Nek5000/nekRS#417]
With a CHT pipe mesh that has inner diameter = 1, outer diameter = 4/3, when I specify a constant mean velocity of 1.0, it results in a velocity field with mean streamwise velocity of 1.778. It appears this is due to the mean calculated using on the thermal domain.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/9ae887200454a3409e8a0c324bde9989815716c3
