### ISSUE TITLE
Pass `--help` option to `nrsmpi`

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#421]
If the user has a mistake in the `.par` file, you can pass `--help par` to `nekrs` to print out a useful table of valid parameters. It would be helpful if the `--help` were also passed to `nrsmpi`, which is the much more likely command people will use to run NekRS.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/9ae887200454a3409e8a0c324bde9989815716c3
