### ISSUE TITLE
Increase the length of the string for filenames.

### ISSUE THREAD

**Issue by yslan** [Nek5000/nekRS#437]
Our reader fails when the path to the file is too long.
It will cut-off the path and eventually the reader can't find the file.

For example: 
```
/gpfs/alpine/csc262/proj-shared/ylan/pebble_pack031321/rod1717_crusher_mem_tests/run_nekrs_summit/rod1717_17/work_profiling/rod1717_
ERROR:  Cannot find re2 file!  ierr= 40
```

I'm always frustrated to come up with a proper name for new folders and new files.
As a bad habit, I have many folders with long names.
It's also hard to rename the folder afterward since it will intervene the running jobs and workflow. 

Also, on HPC platform, the project folder is already occupied 1/4 of the length.

**Describe the solution you'd like**
Do we really need the absolute path?
Maybe increase the 132 characters limit? or even simply add a check in nekrs --setup will help.

**Comment by stgeke** [comment]
This is a limitation in nek5000 not nekRS.
