### ISSUE TITLE
print flops/rank

### ISSUE THREAD

**Issue by fischer1** [Nek5000/nekRS#461]
NekRS currently writes the total flops for the simulation (presumably skipping the setup phase).

It would be nice to also have "flops per rank" written out so that 

grep -iIR flops *

would reveal this figure automatically.   Currently we have to also figure out the number of ranks
and then do the division, which is challenging if you're surveying a huge directory structure with logfiles.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/833f1b5a9e2e38279e93975c4227b7812fed8155
