### ISSUE TITLE
Host coordinate arrays for t-mesh are overwritten

### ISSUE THREAD

**Issue by MalachiTimothyPhillips** [Nek5000/nekRS#462]
Shallow copy of t-mesh coordinates into v-mesh at:

https://github.com/Nek5000/nekRS/blob/8ee9c381f86f5f70867d942616e585ee726a8ca1/src/mesh/meshSetup.cpp#L348

cause the t-mesh coordinates on the host-side to be overwritten during the `meshHaloPhysicalNodes` call:

https://github.com/Nek5000/nekRS/blob/8ee9c381f86f5f70867d942616e585ee726a8ca1/src/mesh/meshSetup.cpp#L352

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/833f1b5a9e2e38279e93975c4227b7812fed8155
