### ISSUE TITLE
Problem with the example TurbPipePeriodic

### ISSUE THREAD

**Issue by Chaggge** [Nek5000/nekRS#466]
Hi, neks! 
I am new with nekrs.

I have compiled nekrs without errors as it is described at: https://github.com/Nek5000/nekRS.
Then I tried to run TurbPipePeriodic using `mpirun -np 2 nekrs --setup turbPipe.par`. But I faced with the problem:
`Message  : Device: Creating Device
                     CUDA Error [ 101 ]: CUDA_ERROR_INVALID_DEVICE`
```
My configuration:
gcc (Debian 10.2.1-6) 10.2.1 20210110
NVIDIA (R) CUDA Debugger 11.2 release
GPU: GeForce GTX 1050 Ti
```

**Comment by stgeke** [comment]
You're trying to run nekRS on two GPUs but it looks like it was not able to find them. May be there is just one?

**Comment by stgeke** [comment]
Please use Github Discussions for request like this.
