### ISSUE TITLE
Host coordinate arrays for t-mesh are overwritten

### ISSUE THREAD

**Issue by aprilnovak** [Nek5000/nekRS#475]
We need the bug fix for the shallow copy of t-mesh coordinates to be fixed to move forward with a [Cardinal development task](https://github.com/neams-th-coe/cardinal/pull/532).

The bug has been fixed in NekRS (see past PR here: https://github.com/Nek5000/nekRS/issues/462), but seems to only be accessible from the private repository. Can that pull request content please be merged into the publicly accessible `next` branch?

**Comment by stgeke** [comment]
Duplicate of #462
