### ISSUE TITLE
Simulation crashes at same time step for one supercomputer but runs successfully on other

### ISSUE THREAD

**Issue by Platinumd1991** [Nek5000/nekRS#479]
Hi,

I don;t know why my simulation crashes on one supercomputer (GPU) but not the other (CPU). I have tried to reduce delta t to lower the courant number but my simulation still crashes as the same exact timestep as posted below when I use (NekRS) but this same case runs successfully on Nek5000. What could be the cause of this? My collegues are also having the same issue with their cases between the twosupercomputers.

> > step= 52598 t= 1.82207840e+02 dt=8.0e-05 C= 4.27 UVW: 2 P: 22 eTime=
> > 2.11e-01, 2.71779e+03 s
> > step= 52599 t= 1.82207920e+02 dt=8.0e-05 C= 5.82 UVW: 3 P: 23 eTime=
> > 2.09e-01, 2.71800e+03 s
> > step= 52600 t= 1.82208000e+02 dt=8.0e-05 C= 8.76 UVW: 3 P: 25 eTime=
> > 2.30e-01, 2.71823e+03 s
> > copying solution to nek
> > calling nek_userchk ...
> > 52600 1.82208000000E+02 7.26226313888E+00 7.26559569350E+00
> > -3.33255462393E-03 1dragx
> > 52600 1.82208000000E+02 -2.88376652997E-03 -2.62383438671E-03
> > -2.59932143255E-04 1dragy
> > 52600 1.82208000000E+02 -2.16552739071E-04 1.40683273030E-16
> > -2.16552739071E-04 1dragz
> > 52600 1.82208000000E+02 7.26226313888E+00 7.26559569350E+00
> > -3.33255462393E-03 2dragx
> > 52600 1.82208000000E+02 -2.88376652997E-03 -2.62383438671E-03
> > -2.59932143255E-04 2dragy
> > 52600 1.82208000000E+02 -2.16552739071E-04 1.40683273030E-16
> > -2.16552739071E-04 2dragz
> > dump history points
> > step= 52601 t= 1.82208080e+02 dt=8.0e-05 C= 15.38 UVW: 3 P: 30 eTime=
> > 3.06e-01, 2.71854e+03 s
> > step= 52602 t= 1.82208160e+02 dt=8.0e-05 C= 45.05 UVW: 3 P: 37 eTime=
> > 3.26e-01, 2.71886e+03 s
> > Unreasonable CFL! Dying ...

**Comment by stgeke** [comment]
Please use https://github.com/Nek5000/nekRS/discussions for things like that.
