### ISSUE TITLE
Incorrect boundary device function check

### ISSUE THREAD

**Issue by yslan** [Nek5000/nekRS#482]
**This is a feature request**
We use regex to check whether boundary condition function is declared inside the oudf.
```
    found = std::regex_search(buffer.str(), std::regex(R"(\s*void\s+pressureDirichletConditions)"));
```

However, that will omit the cases when user commenting out the entire function. For example,
- Case 1   
  ```
  // void pressureDirichletConditions(bcData *bc) { 
  // ...
  //} 
  ```

- Case 2   
  ```
  /*
  void pressureDirichletConditions(bcData *bc) { }
  */
  ```

**Describe the solution you'd like**
I don't know how to rule out the case 2, but at least we can do the following change to make sure it ignores the case 1.
```
(^\s*void\s+pressureDirichletConditions)
```

**Additional context**
Maybe we can perform some style check when we preprocessing the oudf / udf / usr.    
This is totally related to user specific behavior. For example, users should usually do the following.
```
void pressureDirichletConditions(bcData *bc) { 
/*
...
*/
}
```

However, we support empty oudf file as well. It's logical for some users to do vimdiff and simply comment out the difference.

**Comment by stgeke** [comment]
The new upcoming version will allow you add an okl section `@oklBegin{ ... }@oklEnd` into the udf instead using an oudf. This will also fix the reported issue.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/833f1b5a9e2e38279e93975c4227b7812fed8155
