### ISSUE TITLE
Unhelpful error message if scalar00 is skipped

### ISSUE THREAD

**Issue by anshchaube** [Nek5000/nekRS#484]
**Is your feature request related to a problem? Please describe.**
If I skip adding `scalar00` or a `TEMPERATURE` block to my par file and move on to adding `scalar01` and `scalar02` (say, for k-tau RANS), I get an unhelpful error message:
```
ERROR: filterNc must be at least 1, but is set to -1
```
which does not point to the issue that scalar IDs seem to be required to start from 0.

**Describe the solution you'd like**
A check for this user error that prints a more helpful error message along the lines of "please assign scalar id 00 to your first scalar", or allowing for scalar IDs to start from any arbitrary integer.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/833f1b5a9e2e38279e93975c4227b7812fed8155
