### ISSUE TITLE
Build fails when using AppleClang

### ISSUE THREAD

**Issue by OsKnoth** [Nek5000/nekRS#490]
Within clang as the standard C/C++ compiler I get the follwing error by executing ./nrsconfig

CMake Error at /usr/local/Cellar/cmake/3.19.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

This happens on my MacBookPro (Intel) and my MacMini (M2).

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/833f1b5a9e2e38279e93975c4227b7812fed8155
