### ISSUE TITLE
Next: pointInterpolation only considers the vmesh

### ISSUE THREAD

**Issue by joneuhauser** [Nek5000/nekRS#496]
I've just tried the new `pointInterpolation` functionality in v23. The interface is very nice, thanks for that! Similar to https://github.com/Nek5000/nekRS/pull/495, `pointInterpolation` only considers the `meshV` at the moment, i.e. I get a warning about "outside points" when interpolating the temperature within the tmesh. 

I understand that usually interpolation is only relevant in the fluid (Lagrangian particles etc). But for extracting statistics, it would be useful if that worked. On first glance it seems to be a oneline fix in `pointInterpolation.cpp:31` - which works for me - or the interface is expanded to include passing a `mesh_t*`.

Should I prepare a MR or would this be duplicated work again?

**Comment by stgeke** [comment]
Thanks for bringing this up. We will address it internally -  no need for a PR.

**Comment by stgeke** [comment]
Should be fixed in latest `next`

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/833f1b5a9e2e38279e93975c4227b7812fed8155
