### ISSUE TITLE
Select GPU Parallel

### ISSUE THREAD

**Issue by Guoyfbb** [Nek5000/nekRS#529]
**Expected behavior**
I have two GPUs in my computer, and when one of my GPUs is running the other program, I want to run Nekrs, but the program reports an error. I would like to ask how to choose the GPU model before running the program to avoid the above problem..

**Comment by yslan** [comment]
What error did you see?

What GPU vender you have?
If it's nvidia, maybe try 
CUDA_VISIBLE_DEVICES=1 
to skip the first GPU?

**Comment by Guoyfbb** [comment]
I apologize for not being very accurate in my expression. Where should I add such a sentence to choose a GPU? And when my simulated GPU memory occupies more than 1 of the GPU memory, can I do GPU parallelism, and if so, in which part of the program can it be reflected?
