### ISSUE TITLE
timeStepConverged in UDF_ExecuteStep

### ISSUE THREAD

**Issue by dkaddar** [Nek5000/nekRS#591]
Hey,
I moved to the most recent commit on ```next``` (c6a366d) and experience some issues with the tavg utility.
When running the turbPipe example, tavg::run() in turbPipe.udf:240 is never executed, resulting in fields with just 0 values being written. The reason for that is the bool nrs->timeStepConverged that is never returning true after the first timestep.

I didn't investigate which commit introduced this issue, but looking at timeStepper.cpp:620 there is a convergence check with assignment to a local variable which is not propagated to the member variable before calling udf.executeStep on line 630.

I can reproduce the issue on JUWELS Booster as well as on my local machine regardless of the backend (CUDA, serial).

Best,
Driss

**Comment by stgeke** [comment]
Fixed in `next`.
