### ISSUE TITLE
AVM par error message about missing noiseThreshold qualifier is misleading

### ISSUE THREAD

**Issue by dsteinmo** [Nek5000/nekRS#595]
**Describe the bug**
If the noiseThreshold qualifier is left out when including the AVM stabilizer in a .par file, the options parser complains that 'absoluteTol' qualifier is missing. However, it would be more useful to indicate to the user that the expected qualifier is called 'noiseThreshold.'

**To Reproduce**
1. Edit a par file that includes a scalar.
2. In the scalar section add a line like this: `regularization = avm+c0`
3. Run `nekrs --setup rbc.par`
4. Error message suggests that `absoluteTol` is a missing `avm` qualifier, when it actually wants `noiseThreshold` qualifier.

**Expected behavior**
I would expect the error message to mention `noiseThreshold`, not `absoluteTol`.

**Version**
 - ''next' branch latest.

**Comment by dsteinmo** [comment]
Fix for this in PR# https://github.com/Nek5000/nekRS/pull/596.

**Comment by dsteinmo** [comment]
@kris-rowe, FYI.

**Comment by stgeke** [comment]
Fixed in `next`.
