### ISSUE TITLE
Add launch bound support to OCCA

### ISSUE THREAD

**Issue by stgeke** [Nek5000/nekRS#89]
Some compilers assume they can use all available registers (e.g. 255) if no kernel launch bounds are specified. This can cause the kernel to crash at runtime because too many resources are requested (see #199).  

What follows is a list of all thread configurations used in the code. Some of them clearly violate the safe choice of <= 256 depending on the polynomialOrder.

simple 1D kernels: BLOCKSIZE (256)
typical tensor product kernel: Nq * Nq
oververlapping Schwarz smoother: (Nq+2) * (Nq+2)
advection kernels: NqCub * NqCub (where NqCub is typically 3Nq/2 - 1)

Occa issue: https://github.com/libocca/occa/issues/307

**Comment by MalachiTimothyPhillips** [comment]
- ellipticDivGradHex3D
- ellipticPreconCoarsenHex3D
- ellipticPreconProlongateHex3D

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/7a55f459cd9b42129d0d3312dac8dd614cdb50d0
