### ISSUE TITLE
Termination after building nek..done

### ISSUE THREAD

**Issue by brathod2** [Nek5000/nekRS#92]
![NekRS issue](https://user-images.githubusercontent.com/66644819/85052427-e41b5b00-b166-11ea-85ce-f2a49f214241.PNG)

I would be grateful for any help in this regard. I am trying to run one of the example files. The program was successfully installed. Kindly let me know if there are any log files that might help to pinpoint the above issue. 
![image](https://user-images.githubusercontent.com/66644819/85052570-280e6000-b167-11ea-90f3-c626a30149a8.png)

**Comment by stgeke** [comment]
This was caused by some deprecated MPI function we used in nek5000. I fixed it. Can you please clone the nekRS repo again and give it a try.

**Comment by brathod2** [comment]
Yeah, I will post the results as son as possible. Thanks for it.

**Comment by brathod2** [comment]
![image](https://user-images.githubusercontent.com/66644819/85097704-5b340c00-b1c6-11ea-8a28-4ba77dc3c301.png)
It worked! Thanks a lot again. Would you mind to consider the same error with the Nek5000 version as well. I was trying to run Nek5000 simultaneously and faced similar situation.
![Nek5000 issue](https://user-images.githubusercontent.com/66644819/85097820-bd8d0c80-b1c6-11ea-9e2b-1f68b9be7719.PNG)
